import { v4 as uuid } from 'uuid';
const dummyData = [
	{
		id: uuid(),
		name: 'Cola',
		categories: ['Beverages', 'Soft Drinks'],
		price: 1.49,
		cost: 100,
		stock: 120,
	},
	{
		id: uuid(),
		name: 'Caesar Salad',
		categories: ['Appetizers', 'Salads'],
		price: 6.99,
		cost: 400,
		stock: 60,
	},
	{
		id: uuid(),
		name: 'Spaghetti Carbonara',
		categories: ['Main Courses', 'Pasta Dishes'],
		price: 10.99,
		cost: 700,
		stock: 50,
	},
	{
		id: uuid(),
		name: 'Roasted Asparagus',
		categories: ['Side Dishes', 'Vegetables'],
		price: 4.99,
		cost: 300,
		stock: 40,
	},
	{
		id: uuid(),
		name: 'Red Velvet Cake',
		categories: ['Desserts', 'Cakes'],
		price: 5.99,
		cost: 350,
		stock: 30,
	},
	{
		id: uuid(),
		name: 'Balsamic Vinaigrette',
		categories: ['Condiments', 'Salad Dressings'],
		price: 0.99,
		cost: 50,
		stock: 100,
	},
	{
		id: uuid(),
		name: 'Tomatoes',
		categories: ['Ingredients', 'Vegetables'],
		price: 2.49,
		cost: 150,
		stock: 80,
	},
	{
		id: uuid(),
		name: 'Paper Napkins',
		categories: ['Supplies', 'Napkins'],
		price: 0.05,
		cost: 25,
		stock: 500,
	},
	{
		id: uuid(),
		name: 'Dishwashing Liquid',
		categories: ['Cleaning Supplies', 'Detergents'],
		price: 3.99,
		cost: 20,
		stock: 10,
	},
	{
		id: uuid(),
		name: 'Restaurant T-Shirt',
		categories: ['Miscellaneous', 'Promotional Items'],
		price: 15.99,
		cost: 300,
		stock: 50,
	},
	{
		id: uuid(),
		name: 'Orange Juice',
		categories: ['Beverages', 'Juices'],
		price: 2.99,
		cost: 150,
		stock: 80,
	},
	{
		id: uuid(),
		name: 'Tomato Soup',
		categories: ['Appetizers', 'Soups'],
		price: 4.49,
		cost: 250,
		stock: 40,
	},
	{
		id: uuid(),
		name: 'Grilled Cheese Sandwich',
		categories: ['Main Courses', 'Sandwiches'],
		price: 7.49,
		cost: 450,
		stock: 70,
	},
	{
		id: uuid(),
		name: 'Mashed Potatoes',
		categories: ['Side Dishes', 'Potatoes'],
		price: 3.99,
		cost: 200,
		stock: 60,
	},
	{
		id: uuid(),
		name: 'Chocolate Chip Cookie Dough Ice Cream',
		categories: ['Desserts', 'Ice Cream'],
		price: 6.99,
		cost: 400,
		stock: 25,
	},
	{
		id: uuid(),
		name: 'Tomato Ketchup',
		categories: ['Condiments', 'Ketchup'],
		price: 0.49,
		cost: 30,
		stock: 150,
	},
	{
		id: uuid(),
		name: 'Chicken Breast',
		categories: ['Ingredients', 'Meat'],
		price: 5.99,
		cost: 350,
		stock: 100,
	},
	{
		id: uuid(),
		name: 'Takeout Containers',
		categories: ['Supplies', 'Containers'],
		price: 0.25,
		cost: 50,
		stock: 200,
	},
	{
		id: uuid(),
		name: 'Scrubbing Sponge',
		categories: ['Cleaning Supplies', 'Sponges'],
		price: 1.99,
		cost: 30,
		stock: 20,
	},
	{
		id: uuid(),
		name: "Chef's Special Seasoning Blend",
		categories: ['Miscellaneous', 'Special Products'],
		price: 7.99,
		cost: 150,
		stock: 30,
	},
];

export default dummyData;
